// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpDZYWZIpHz0K6uRWNgARvLE7HQXFuP8k',
    appId: '1:388175489657:web:5ff1a1bc4e78558bc202a8',
    messagingSenderId: '388175489657',
    projectId: 'pharmacy-layout',
    authDomain: 'pharmacy-layout.firebaseapp.com',
    storageBucket: 'pharmacy-layout.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLFFPO9AAmJ98Lyy4q0E4jVAgoKFfXuuI',
    appId: '1:388175489657:android:e48dfb6a413003ffc202a8',
    messagingSenderId: '388175489657',
    projectId: 'pharmacy-layout',
    storageBucket: 'pharmacy-layout.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpDZYWZIpHz0K6uRWNgARvLE7HQXFuP8k',
    appId: '1:388175489657:web:19c7628dc0cd5b71c202a8',
    messagingSenderId: '388175489657',
    projectId: 'pharmacy-layout',
    authDomain: 'pharmacy-layout.firebaseapp.com',
    storageBucket: 'pharmacy-layout.appspot.com',
  );
}
